import * as Redux from 'redux';
import { REHYDRATE } from 'redux-persist/constants';
import { FanchartSettings } from '../Store/Fanchart';
import { PedigreeSettings } from '../Store/Pedigree';
import { PersonSet, HistoryItem } from '../Store/Person';
import { actionCreator } from '../Store/Actions';
import { GenealogyEventSet } from '../Store/Event';

export interface AppState {
   pedigree: PedigreeSettings;
   fanchart: FanchartSettings;
   persons: PersonSet;        // details for all persons
   events: GenealogyEventSet; // all known events
   history: HistoryItem[];    // id of persons recently visited
}

export type GPDispatch = Redux.Dispatch<AppState>;
export type GPStore = Redux.Store<AppState>;

/**
 * Rehydrate action generated by redux-persist
 */
export const rehydrate = actionCreator<AppState>(REHYDRATE);
