# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-14 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
