# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0005_MIL_to_MILT'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(help_text='Type oof rule')),
                ('name', models.TextField(blank=True, help_text='Description of the style', null=True)),
                ('sequence_number', models.IntegerField(default=1)),
                ('style_fill', models.TextField(blank=True, help_text='Color to fill elements', null=True)),
                ('style_color', models.TextField(blank=True, help_text='Color for text', null=True)),
                ('style_stroke', models.TextField(blank=True, help_text='Color for lines', null=True)),
                ('style_font_weight', models.TextField(blank=True, help_text='Thickness of text (normal, bold)', null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geneaprove.Rule')),
            ],
            options={
                'db_table': 'rule',
                'ordering': ('sequence_number', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RulePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(help_text="What we are testing, for instance 'name'")),
                ('operator', models.TextField(choices=[('=', '='), ('i=', 'i='), ('!=', '!='), ('i!=', 'i!='), ('in', 'in'), ('iin', 'iin'), ('contains', 'contains'), ('icontains', 'icontains'), ('!contains', '!contains'), ('!icontains', '!icontains'), ('<', '<'), ('<=', '<='), ('>=', '>='), ('>', '>')], max_length=10)),
                ('value', models.TextField(help_text='What it should match (either a string or a list)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='geneaprove.Rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the neme', unique=True)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='name',
            field=models.TextField(db_column='name'),
        ),
        migrations.AddField(
            model_name='rule',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='geneaprove.Theme'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geneaprove.Rule'),
        ),
    ]
