# Generated by Django 2.1.7 on 2019-03-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0007_theme_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic_part_type',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='rulepart',
            name='operator',
            field=models.TextField(choices=[('=', '='), ('=int', '=int'), ('=bool', '=bool'), ('=pers', '=pers'), ('i=', 'i='), ('!=', '!='), ('!=int', '!=int'), ('!=bool', '!=bool'), ('i!=', 'i!='), ('in', 'in'), ('in_int', 'in_int'), ('iin', 'iin'), ('contains', 'contains'), ('icontains', 'icontains'), ('!contains', '!contains'), ('!icontains', '!icontains'), ('<str', '<str'), ('<=str', '<=str'), ('>=str', '>=str'), ('>str', '>str'), ('<int', '<int'), ('<=int', '<=int'), ('>=int', '>=int'), ('>int', '>int')], max_length=10),
        ),
    ]
