# Generated by Django 2.1.7 on 2019-03-18 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0008_auto_20190315_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='persona',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='geneaprove.Persona'),
        ),
    ]
