# Generated by Django 3.0.2 on 2022-06-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0009_main_id_in_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2c',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher'),
        ),
        migrations.AlterField(
            model_name='p2e',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher'),
        ),
        migrations.AlterField(
            model_name='p2g',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher'),
        ),
        migrations.AlterField(
            model_name='p2p',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher'),
        ),
        migrations.AlterField(
            model_name='source',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher'),
        ),
    ]
