# Generated by Django 3.0.2 on 2022-06-21 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0012_repository_last_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='G2C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(help_text='Explains why the assertion (deduction, comments,...)', null=True)),
                ('disproved', models.BooleanField(default=False)),
                ('last_change', models.DateTimeField(default=django.utils.timezone.now, help_text='When was the assertion last modified')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='geneaprove.Characteristic')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='geneaprove.Group')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Researcher')),
                ('source', models.ForeignKey(help_text='An assertion comes from no more than one source. It can also come from one or more other assertions through the assertion_assertion table, in which case source_id is null', null=True, on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Source')),
                ('surety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneaprove.Surety_Scheme_Part')),
            ],
            options={
                'db_table': 'g2c',
            },
        ),
    ]
