# Generated by Django 3.0.2 on 2022-06-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneaprove', '0013_g2c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='display_name',
        ),
    ]
